name: "Roverr"
version: "4.2.1"
slug: "roverr"
description: "Your personal media manager. Organizes downloads for Jellyfin, Emby, Kodi, Plex, and other media servers."
url: "https://github.com/datmospro/ha-addons/tree/main/roverr"
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - config:rw
  - share:rw
  - media:rw
options: {}
schema: {}
ports:
  8092/tcp: 8092
webui: "http://[HOST]:[PORT:8092]"